version: '3'

services:
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=370'
    ports:
      - '5555:5432'
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: task-manager
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    volumes:
      - './postgresql/pg.sql:/docker-entrypoint-initdb.d/pg.sql'

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - './rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  permission-service:
    tty: false
    build: ./permission_service
    command: sh -c "make backend-run-minimal"
    ports:
      - '8080:8080'

  alertmanager:
    build:
      context: ./alerting/
    command:
      - '--config.file=/etc/prometheus/alertmanager.yaml'
    network_mode: 'host'
    ports:
      - '9093:9093'

  prometheus:
    tty: false
    build:
      context: ./monitoring/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    network_mode: 'host'
    depends_on:
      - alertmanager
    ports:
      - '9090:9090'
